sudo: reqired
services:
  - docker

before_install:
  - docker build -t daniladanila2378/react-test -f ./client/Dockerfile.spec ./client

script:
  - docker run daniladanila2378/react-test npm test -- --coverage

after_success:
  - docker build -t daniladanila2378/ico-list-client ./client
  - docker build -t daniladanila2378/ico-list-nginx ./nginx
  - docker build -t daniladanila2378/ico-list-server ./server
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take images and push to docker hub
  - docker push daniladanila2378/ico-list-client
  - docker push daniladanila2378/ico-list-nginx
  - docker push daniladanila2378/ico-list-server

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "eu-central-1"
  app: "ico-list"
  env: "IcoList-env"
  bucket_name: "elasticbeanstalk-eu-central-1-559249728360"
  bucket_path: ico-list
  on:
    branch: master